image: "rust:latest"

stages:
    - lint
    - build
    - test

build_latest:
    stage: build
    image: rust:latest
    script:
        - rustc --version
        - cargo --version  # Print version info for debugging
        - cargo build --verbose

test_latest:
    stage: test
    image: rust:latest
    needs: ["build_latest"]
    script:
        - cargo test --verbose

clippy:
    stage: lint
    image: rust:latest
    script:
        - rustup component add clippy
        - cargo clippy -- -D warnings

rustfmt:
    stage: lint
    image: rust:latest
    script:
        - rustup component add rustfmt
        - cargo fmt -- --check

build_nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
        - rustc --version
        - cargo --version  # Print version info for debugging
        - cargo build --verbose
    allow_failure: true

test_nightly:
    stage: test
    image: rustlang/rust:nightly
    needs: ["build_nightly"]
    script:
        - cargo test --verbose
