image: "rust:latest"

stages:
    - build
    - test
    - lint

build_latest:
    stage: build
    allow_failure: false
    image: rust:latest
    needs: []
    script:
        - rustc --version
        - cargo --version  # Print version info for debugging
        - cargo build --verbose

test_latest:
    stage: test
    allow_failure: false
    image: rust:latest
    needs: ["build_latest"]
    script:
        - cargo test --verbose

clippy:
    stage: lint
    allow_failure: true
    image: rust:latest
    needs: []
    script:
        - rustup component add clippy
        - cargo clippy -- -D warnings

rustfmt:
    stage: lint
    allow_failure: true
    image: rust:latest
    needs: []
    script:
        - rustup component add rustfmt
        - cargo fmt -- --check

build_nightly:
    stage: build
    allow_failure: true
    image: rustlang/rust:nightly
    needs: []
    script:
        - rustc --version
        - cargo --version  # Print version info for debugging
        - cargo build --verbose

test_nightly:
    stage: test
    allow_failure: true
    image: rustlang/rust:nightly
    needs: []
    needs: ["build_nightly"]
    script:
        - cargo test --verbose
