[package]
name = "wyrd"
version = "0.1.0"
authors = ["Alex Barber <alex@dangerzonegames.com>"]
edition = "2021"
description = "an entity component system created for TimberWolf"
license = "MIT"
repository = "https://gitlab.com/DangerInteracive/TimberWolf/Wyrd"

[dependencies]
armory = "0.1.0"
